### ISSUE TITLE
[Enhancement] Use built -in support for LSP

### ISSUE THREAD

**Issue by l0stlink** [talha-akram/anvil#2]
Neovim 5.x has built in support for LSP so instead of relying on plugins for LSP support we can use it instead.

- it should have feature parity with most popular LSP providers for vim/Neovim.
- ideally most of the code should be lua based for better performance and sane syntax.
- should be easy to disable for those who don't want to use it.
- would be good to have LSP status  in the status line.

**Comment by talha-akram** [comment]
fixed in #4 only builtin LSP is supported now as it is now in stable release of neovim.
